services:
  webapplication1:
    image: webapplication1
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile

  bravix.host:
    image: bravix.host
    build:
      context: .
      dockerfile: src/Bravix.Host/Dockerfile

